config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :artworks

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  has_attached_file :monsterdrawing, styles: {
    thumb: '100x100>',
    square: '400x400#',
    medium: '900x500>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :monsterdrawing, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController

  def index
    @artworks = Artwork.order(created_at: :desc)

  end

  def show
    @artwork = Artwork.find(params[:id])
  end

  def new
    @artwork = Artwork.new
  end

  def create

    @artwork = Artwork.new(artwork_params)

    if @artwork.save
      redirect_to @artwork, notice: 'Your drawing was successfully saved.'
     else
      render Rails.application.routes.recognize_path(request.referer)[:action]
    end
  end

  private

  def artwork_params
    params.require(:artwork).permit(:monsterdrawing, :name, :artist)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/_arms.html.erb
<div class="drawer">
<%= image_tag('arm1.png', class: "part-button pb-circle") %>
</div>

app/views/artworks/_bottomteeth.html.erb
<div class="gums">
  <div class="row">
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>
    <div class="drawer-tab-no-click"></div>

  </div>
</div>
<div class="pre-gums"></div>

<!-- Start footer -->
<div class="footer">
  <div class="row">

    <div class="small-3 columns">
      <div class="button small status-button" id="clear">Clear</div>
      <div class="button small" id="save">Save</div>
    </div>

    <!-- This div is hidden by default -->
    <div id="monster-details">
      <div class="small-3 columns">
        <%= form_for @artwork, url: {controller: 'artworks', action: 'create'}, html: {id: 'frm'} do |f| %>
          <%= f.hidden_field :monsterdrawing, id: 'data' %>
          <p>Title</p>
          <%= f.text_field :name, placeholder: 'Harold' %>
      </div>

      <div class="small-3 columns">
          <p>Created by</p>
          <%= f.text_field :artist, placeholder: 'Emily' %>
      </div>

       <div class="small-3 columns">
         <a href="#themain" class="button small" id="submit">Submit</a>
         <% end %>
       </div>

    </div> <!-- End monter details section -->

  </div> <!-- End Row -->
</div> <!-- End footer -->
<!-- Sub footer -->

app/views/artworks/_eyes.html.erb
<div class="drawer">
<%= image_tag('eye1.png', class: "part-button pb-circle") %>
<%= image_tag('eye2.png', class: "part-button pb-circle") %>
<%= image_tag('eye3.png', class: "part-button pb-circle") %>
<%= image_tag('eye4.png', class: "part-button pb-circle") %>
<%= image_tag('eye5.png', class: "part-button pb-circle") %>
<%= image_tag('eye6.png', class: "part-button pb-circle") %>
<%= image_tag('eye7.png', class: "part-button pb-circle") %>
<%= image_tag('eye8.png', class: "part-button pb-circle") %>
<%= image_tag('eye9.png', class: "part-button pb-circle") %>
<%= image_tag('eye10.png', class: "part-button pb-circle") %>

</div>

app/views/artworks/_horns.html.erb
<div class="drawer">
<%= image_tag('horn1.png', class: "part-button pb-circle") %>


</div>

app/views/artworks/_legs.html.erb
<div class="drawer">
<%= image_tag('leg1.png', class: "part-button pb-circle") %>
</div>

app/views/artworks/_mouths.html.erb
<div class="drawer">
<%= image_tag('mouth1.png', class: "part-button pb-circle") %>
<%= image_tag('mouth2.png', class: "part-button pb-circle") %>
<%= image_tag('mouth3.png', class: "part-button pb-circle") %>
<%= image_tag('mouth4.png', class: "part-button pb-circle") %>

</div>

app/views/artworks/_noses.html.erb
<div class="drawer">
<%= image_tag('nose1.png', class: "part-button pb-circle") %>
<%= image_tag('nose2.png', class: "part-button pb-circle") %>
<%= image_tag('nose3.png', class: "part-button pb-circle") %>
<%= image_tag('nose4.png', class: "part-button pb-circle") %>
<%= image_tag('nose5.png', class: "part-button pb-circle") %>
<%= image_tag('nose6.png', class: "part-button pb-circle") %>
<%= image_tag('nose7.png', class: "part-button pb-circle") %>
</div>

app/views/artworks/_tails.html.erb
<div class="drawer">
<%= image_tag('tail1.png', class: "part-button pb-circle") %>
</div>

app/views/artworks/index.html.erb
<div class="footer">
  <div class="title">
    <%= link_to 'Create', new_artwork_path, class: "new-links" %>
    <%= link_to "Monster Toolbox", root_path %>
    <%= link_to 'Browse', artworks_path, class: "new-links" %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <div class="grid">
      <% @artworks.each do |artwork| %>
        <div class="cell">
            <%= link_to image_tag(artwork.monsterdrawing.url(:square), class: "gallery-item"), artwork_path(artwork.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/artworks/new.html.erb
<div class="footer">
  <div class="title">
    <%= link_to 'Create', new_artwork_path, class: "new-links" %>
    <%= link_to "Monster Toolbox", root_path %>
    <%= link_to 'Browse', artworks_path, class: "new-links" %>
  </div>
</div>

<div class="dark">
  <div class="row">

    <div id="eyes">
      <div class="small-12 columns" >
        <%= render "eyes" %>
      </div>
    </div>

    <div id="mouths">
      <div class="small-12 columns" >
        <%= render "mouths" %>
      </div>
    </div>

    <div id="noses">
      <div class="small-12 columns" >
        <%= render "noses" %>
      </div>
    </div>

    <div id="ears">
      <div class="small-12 columns" >
        <%= render "ears" %>
      </div>
    </div>

    <div id="horns">
      <div class="small-12 columns" >
        <%= render "horns" %>
      </div>
    </div>

    <div id="arms">
      <div class="small-12 columns" >
        <%= render "arms" %>
      </div>
    </div>

    <div id="legs">
      <div class="small-12 columns" >
        <%= render "legs" %>
      </div>
    </div>

    <div id="tails">
      <div class="small-12 columns" >
        <%= render "tails" %>
      </div>
    </div>

    <div id="hair">
      <div class="small-12 columns" >
        <%= render "hair" %>
      </div>
    </div>

  </div><!-- End dark -->
</div> <!-- End row -->



<!-- Top category tabs -->
<div class="pre-gums"></div>
<div class="gums">
  <div class="row">
    <div class="drawer-tab" id="eyecategory"><p>eyes</p></div>
    <div class="drawer-tab" id="mouthcategory"><p>mouths</p></div>
    <div class="drawer-tab" id="nosecategory"><p>noses</p></div>
    <div class="drawer-tab" id="earcategory"><p>ears</p></div>
    <div class="drawer-tab" id="horncategory"><p>horns</p></div>
    <div class="drawer-tab" id="armcategory"><p>arms</p></div>
    <div class="drawer-tab" id="legcategory"><p>legs</p></div>
    <div class="drawer-tab" id="tailcategory"><p>tails</p></div>
    <div class="drawer-tab" id="haircategory"><p>hair</p></div>
  </div>
</div>
<!-- Canvas and transform toolbar row -->
<div class="canvas">
  <div class="row ">

    <!-- Transform Toolbar -->
    <div class="small-1 large-1 columns">
      <div id="transform">

        <div class="transform-button" id="remove-button">
            <i class="fa fa-trash-o fa-2x"></i>
        </div>
        <br>

        <div class="transform-button" id="rotate-left">
          <i class="fa fa-undo fa-2x"></i>
        </div>
        <br>

        <div class="transform-button" id="rotate-right">
          <i class="fa fa-rotate-right fa-2x"></i>
        </div>
        <br>

        <div class="transform-button " id="bigger">
          <i class="fa fa-expand fa-2x"></i>
        </div>
        <br>

        <div class="transform-button" id="smaller">
          <i class="fa fa-compress fa-2x"></i>
        </div>
        <br>

        <div class="transform-button" id="flip-vertical">
          <i class="fa fa-arrows-v fa-2x"></i>
        </div>
        <br>

        <div class="transform-button" id="flip-horizontal">
          <i class="fa fa-arrows-h fa-2x"></i>
        </div>
        <br>

        <div class="transform-button cancel" id="cancel">
          <i class="fa fa-times fa-2x"></i>
        </div>

      </div><!-- End transform div -->
    </div> <!-- End small 1 column -->

    <!-- Here's the canvas! -->
    <div class="small-10 large-10 columns">
      <canvas id="monsterCanvas" width="900" height="500"></canvas>
      <p class="tool-tip"><i>Double click a shape on the canvas to transform it.</i></p>
    </div> <!-- End 10 columns -->

    <div class="small-1 large-1 columns">
    &nbsp;
    </div>

  </div> <!-- End row -->
</div> <!-- End canvas -->

<!-- Bottom row of teeth -->
<%= render "bottomteeth" %>

app/views/artworks/show.html.erb
<div class="footer">
  <div class="title">
    <%= link_to 'Create', new_artwork_path, class: "new-links" %>
    <%= link_to "Monster Toolbox", root_path %>
    <%= link_to 'Browse', artworks_path, class: "new-links" %>
  </div>
</div>
<div class="white-spacer"></div>
<div class="row">

  <div class="small-2 columns">
  <h3><strong><%= @artwork.name %> </strong></h3>
  <p>Created by<br><i><%= @artwork.artist %><i></p>
  </div>

  <div class="small-8 columns">

    <%= image_tag @artwork.monsterdrawing.url(:medium), class: "gallery-show" %>

  </div>

  <div class="small-2 columns">
  &nbsp;
  </div>

</div>
<div class="white-spacer"></div>

app/views/home/index.html.erb
<div class="homepage"></div>
<div class="footer">
  <div class="title">
    <%= link_to "Monster Toolbox", root_path %>
  </div>
</div>
<div class="floatontop">
  <div class="circle-button1" >
    <%= link_to 'Create', new_artwork_path, class: "circle-text" %>
  </div>

  <div class="circle-button2" >
    <%= link_to 'Browse', artworks_path, class: "circle-text" %>
  </div>
</div>
<div class="white-spacer"></div>
<div class="row">
  <div class="toolbox text-center">
    <%= image_tag('toolbox.png', class: "text-center") %>
  </div>
  <div class="white-spacer"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Monster Toolbox</title>
    <link href='http://fonts.googleapis.com/css?family=Codystar' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

      <%= yield %>
      <div class="light">
        <div class="row ">
          <div class="small-12 columns">
            <div class="by-line">
              Created by <%= link_to "Katryn McIntosh", "http://linkedin.com/in/katrynmcintosh" %> | <strong>GA Boston </strong>Summer 2014<br>
              <i class="fa fa-code-fork"></i> <%= link_to 'Github Repo', "http://github.com/katrynmc/monstertoolbox" %>
            </div> <!-- End by-line -->
          </div> <!-- End 12 columns -->
        </div> <!-- End row -->
      </div> <!-- End light -->
    <script src="http://code.createjs.com/createjs-2013.12.12.min.js"></script>
    <%= javascript_include_tag "application" %>
  </body>
</html>